name: 'Get Daily Trending and deploy it to my blog'

on:
  push:
    branches: 
      - master
  schedule:
    - cron: '0 0 * * *'
  
jobs:
  trending-spider:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: './source'
          destination-github-username: 'S-W-K'
          destination-repository-name: 'Blog'
          user-email: s979612095@gmail.com
          target-branch: master
